apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
   queries.sql: |
    CREATE DATABASE IF NOT EXISTS mydb;
    USE mydb;
    CREATE TABLE messages (id INT AUTO_INCREMENT PRIMARY KEY, message TEXT);


inside data--> any variable is fine but .sql extension is must. then only inside docker-entrypoint.init.db/san.sql will be exucuted. if there is no sql extension then database wont create
